"""empty message

Revision ID: 917af58cc409
Revises: 97c5b7fb139b
Create Date: 2017-11-14 17:42:55.231336

"""

# revision identifiers, used by Alembic.
revision = '917af58cc409'
down_revision = '97c5b7fb139b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    ### end Alembic commands ###
